root@blockchainvm-1473160896734:/home/ubuntu/stellar# node getTransactions.js GCHJISLRF3GDN7BZHNFFHOYVJEZEPTCVOA2EAHCR3F2B43ZT6LX4MU3Q                                                                                        HJISLRF3GDN7BZHNFFHOYVJEZEPTCVOA2EAHCR3F2B43ZT6LX4MU3Q
Page 1:
[ { _links:
     { self: [Object],
       account: [Object],
       ledger: [Object],
       operations: [Object],
       effects: [Object],
       precedes: [Object],
       succeeds: [Object] },
    id: '89476939ccbea6718d0656f246c93c19adfc6972745c2bc6c2d25db673378f72',
    paging_token: '16067283675779072',
    hash: '89476939ccbea6718d0656f246c93c19adfc6972745c2bc6c2d25db673378f72',
    ledger: [Function],
    created_at: '2016-09-23T10:28:07Z',
    source_account: 'GBS43BF24ENNS3KPACUZVKK2VYPOZVBQO2CISGZ777RYGOPYC2FT6S3K',
    source_account_sequence: '4672924424534',
    fee_paid: 100,
    operation_count: 1,
    envelope_xdr: 'AAAAAGXNhLrhGtltTwCpmqlarh7s1DB2hIkbP//jgzn4Fos/AAAAZAAABEAAA                                                                                        BlWAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAjpRJcS7MNvw5O0pTuxVJMkfMVXA0QBxR2XQebzPy78YAA                                                                                        AAXSHboAAAAAAAAAAAB+BaLPwAAAEC1TVQqJB2spj1+Tz3YuXUjjZhbbuYGLb0oWjle+m3KTSFUbopXY                                                                                        Cf3uqmF0kL+eOQ2O1K2rUGJCY0toIX1uysE',
    result_xdr: 'AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAA=',
    result_meta_xdr: 'AAAAAAAAAAEAAAACAAAAAAA5FRwAAAAAAAAAAI6USXEuzDb8OTtKU7sVST                                                                                        JHzFVwNEAcUdl0Hm8z8u/GAAAAF0h26AAAORUcAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAA                                                                                        AAAAAAAAAAAQA5FRwAAAAAAAAAAGXNhLrhGtltTwCpmqlarh7s1DB2hIkbP//jgzn4Fos/BChdKhMGqe                                                                                        gAAARAAAAZVgAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA',
    fee_meta_xdr: 'AAAAAgAAAAMAORUUAAAAAAAAAABlzYS64RrZbU8AqZqpWq4e7NQwdoSJGz//4                                                                                        4M5+BaLPwQoXUFbfZJMAAAEQAAAGVUAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEAO                                                                                        RUcAAAAAAAAAABlzYS64RrZbU8AqZqpWq4e7NQwdoSJGz//44M5+BaLPwQoXUFbfZHoAAAEQAAAGVYAA                                                                                        AAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAA==',
    memo_type: 'none',
    signatures: [ 'tU1UKiQdrKY9fk892Ll1I42YW27mBi29KFo5Xvptyk0hVG6KV2An97qphdJC/                                                                                        njkNjtStq1BiQmNLaCF9bsrBA==' ],
    self: [Function],
    account: [Function],
    operations: [Function],
    effects: [Function],
    precedes: [Function],
    succeeds: [Function] },
  { _links:
     { self: [Object],
       account: [Object],
       ledger: [Object],
       operations: [Object],
       effects: [Object],
       precedes: [Object],
       succeeds: [Object] },
    id: '8ca0799c605025dda93f500e3657a4b8016071ba40212ddba3583c93f31e14c9',
    paging_token: '16068121194401792',
    hash: '8ca0799c605025dda93f500e3657a4b8016071ba40212ddba3583c93f31e14c9',
    ledger: [Function],
    created_at: '2016-09-23T10:39:56Z',
    source_account: 'GB2O6FHKUEZETX3DQDKSONLWE4LJQ22HK3SZSESAA2YOQWXK32UM2EHU',
    source_account_sequence: '16067249316036609',
    fee_paid: 100,
    operation_count: 1,
    envelope_xdr: 'AAAAAHTvFOqhMknfY4DVJzV2JxaYa0dW5ZkSQAaw6Frq3qjNAAAAZAA5FRQAA                                                                                        AABAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAjpRJcS7MNvw5O0pTuxVJMkfMVXA0QBxR2XQebzPy78YAA                                                                                        AAAAAAAAHc1lAAAAAAAAAAAAereqM0AAABAROsKI8KR7EwwUzHK8U0kaxm86cB5lXVxrWLnaBMboDpms                                                                                        hN3QahnNUC0SDr1nHKaHuVXrcQUZk6oR4rQESwkAA==',
    result_xdr: 'AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAA=',
    result_meta_xdr: 'AAAAAAAAAAEAAAADAAAAAQA5Fd8AAAAAAAAAAHTvFOqhMknfY4DVJzV2Jx                                                                                        aYa0dW5ZkSQAaw6Frq3qjNAAAAFtFBU5wAORUUAAAAAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAA                                                                                        AAAAAAAAAAAwA5FRwAAAAAAAAAAI6USXEuzDb8OTtKU7sVSTJHzFVwNEAcUdl0Hm8z8u/GAAAAF0h26A                                                                                        AAORUcAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAQA5Fd8AAAAAAAAAAI6USX                                                                                        EuzDb8OTtKU7sVSTJHzFVwNEAcUdl0Hm8z8u/GAAAAF7+sfAAAORUcAAAAAAAAAAAAAAAAAAAAAAAAAA                                                                                        ABAAAAAAAAAAAAAAAAAAAA',
    fee_meta_xdr: 'AAAAAgAAAAMAORUUAAAAAAAAAAB07xTqoTJJ32OA1Sc1dicWmGtHVuWZEkAGs                                                                                        Oha6t6ozQAAABdIdugAADkVFAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEAO                                                                                        RXfAAAAAAAAAAB07xTqoTJJ32OA1Sc1dicWmGtHVuWZEkAGsOha6t6ozQAAABdIduecADkVFAAAAAEAA                                                                                        AAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAA==',
    memo_type: 'none',
    signatures: [ 'ROsKI8KR7EwwUzHK8U0kaxm86cB5lXVxrWLnaBMboDpmshN3QahnNUC0SDr1n                                                                                        HKaHuVXrcQUZk6oR4rQESwkAA==' ],
    self: [Function],
    account: [Function],
    operations: [Function],
    effects: [Function],
    precedes: [Function],
    succeeds: [Function] } ]
